package demofillws;

import java.awt.SystemColor;
import streetmaster.fillws.*;

 /** 
  * @author StreetMaster
  * Esempio di utilizzo del servizio WS FILL per la verifica e la normalizzazione degli indirizzi italiani realizzato da StreetMaster Italia
  * 
  * L'end point del servizio è 
  *     http://streetmaster.streetmaster.it/smws/fill?wsdl
  *     
  * Per l'utilizzo registrarsi sul sito http://streetmaster.it e richiedere la chiave per il servizio FILL 
  * 
  * 2016 - Software by StreetMaster (c)
  */

public class FormDemoFill extends javax.swing.JFrame {

    private int curCand=0;
    private TotOutFill totOut=null;
    /**
     * Creates new form DemoVerify
     */
    public FormDemoFill() {
        initComponents();
        this.getContentPane().setBackground(SystemColor.info);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtComuneIn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtIndirizzoIn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtProvIn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtCAPIn = new javax.swing.JTextField();
        jBtnCallVerify = new javax.swing.JButton();
        jTxtKey = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanelOut = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTxtEsito = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtCodErr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtNumCand = new javax.swing.JTextField();
        jBtnPrev = new javax.swing.JButton();
        jPanelCand = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTxtComuneOut = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtProvOut = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtCAPOut = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtFrazioneOut = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtIndirizzoOut = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtRegioneOut = new javax.swing.JTextField();
        jTxtIstatProvOut = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTxtIstatComuneOut = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTxtXOut = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTxtYOut = new javax.swing.JTextField();
        jBtnNext = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo Fill");
        setBackground(java.awt.SystemColor.info);

        jPanelInput.setBackground(java.awt.SystemColor.info);
        jPanelInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInput.setName("Input"); // NOI18N

        jLabel1.setText("Comune:");

        jTxtComuneIn.setName(""); // NOI18N

        jLabel2.setText("Indirizzo:");

        jLabel3.setText("Provincia:");

        jLabel4.setText("CAP:");

        javax.swing.GroupLayout jPanelInputLayout = new javax.swing.GroupLayout(jPanelInput);
        jPanelInput.setLayout(jPanelInputLayout);
        jPanelInputLayout.setHorizontalGroup(
            jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInputLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtComuneIn, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtProvIn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCAPIn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInputLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtIndirizzoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanelInputLayout.setVerticalGroup(
            jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtComuneIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtCAPIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtProvIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtIndirizzoIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jBtnCallVerify.setText("Call Fill");
        jBtnCallVerify.setActionCommand("jBtnCallFill");
        jBtnCallVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCallVerifyActionPerformed(evt);
            }
        });

        jTxtKey.setText("Specificare una chiave per il servizio Fill");

        jLabel5.setText("KEY:");

        jPanelOut.setBackground(java.awt.SystemColor.info);
        jPanelOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Esito:");

        jTxtEsito.setName(""); // NOI18N

        jLabel7.setText("Cod Err:");

        jLabel8.setText("Num Cand:");

        jBtnPrev.setText("<<");
        jBtnPrev.setToolTipText("");
        jBtnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrevActionPerformed(evt);
            }
        });

        jPanelCand.setBackground(java.awt.SystemColor.info);
        jPanelCand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Comune:");

        jTxtComuneOut.setName(""); // NOI18N

        jLabel10.setText("Provincia:");

        jLabel11.setText("CAP:");

        jLabel12.setText("Frazione:");

        jTxtFrazioneOut.setName(""); // NOI18N

        jLabel13.setText("Indirizzo:");

        jLabel15.setText("Regione:");

        jTxtRegioneOut.setName(""); // NOI18N

        jLabel16.setText("Istat Prov:");

        jLabel17.setText("Istat Comune:");

        jLabel18.setText("X:");

        jLabel19.setText("Y:");

        javax.swing.GroupLayout jPanelCandLayout = new javax.swing.GroupLayout(jPanelCand);
        jPanelCand.setLayout(jPanelCandLayout);
        jPanelCandLayout.setHorizontalGroup(
            jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCandLayout.createSequentialGroup()
                        .addGroup(jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCandLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtFrazioneOut, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCandLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtComuneOut, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCandLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtProvOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtCAPOut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCandLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtIstatProvOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(10, 10, 10)
                                .addComponent(jTxtIstatComuneOut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCandLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtRegioneOut, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCandLayout.createSequentialGroup()
                        .addGroup(jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCandLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel13))
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCandLayout.createSequentialGroup()
                                .addComponent(jTxtXOut, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtYOut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtIndirizzoOut))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelCandLayout.setVerticalGroup(
            jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTxtRegioneOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtComuneOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTxtCAPOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtProvOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFrazioneOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17)
                    .addComponent(jTxtIstatComuneOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTxtIstatProvOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtIndirizzoOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanelCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTxtYOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTxtXOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jBtnNext.setText(">>");
        jBtnNext.setToolTipText("");
        jBtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOutLayout = new javax.swing.GroupLayout(jPanelOut);
        jPanelOut.setLayout(jPanelOutLayout);
        jPanelOutLayout.setHorizontalGroup(
            jPanelOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOutLayout.createSequentialGroup()
                        .addComponent(jBtnPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnNext))
                    .addGroup(jPanelOutLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEsito, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCodErr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNumCand, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelOutLayout.setVerticalGroup(
            jPanelOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtEsito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtNumCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtCodErr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnPrev)
                    .addComponent(jBtnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jLabel14.setBackground(java.awt.SystemColor.info);
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Sviluppo\\RepositoryDemo\\VerifyFreeRest_ASPNET\\VerifyFreeRest_ASPNET\\images\\logo-street-master.png")); // NOI18N
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBtnCallVerify)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtKey))
                        .addComponent(jPanelInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnCallVerify)
                            .addComponent(jLabel5)
                            .addComponent(jTxtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanelOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCallVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCallVerifyActionPerformed
        // oggetto client per l'utilizzo del ws FILL
        Fill_Service fillWS=new Fill_Service();   
        Fill fillClient= fillWS.getFillPort();
       
        // valorizzazione input
        InputCommon inFill=new InputCommon();
        inFill.setLocalita(jTxtComuneIn.getText());
        inFill.setProvincia(jTxtProvIn.getText());
        inFill.setCap(this.jTxtCAPIn.getText());
        inFill.setIndirizzo(jTxtIndirizzoIn.getText());
        
        // chiamata al servizio
        totOut=fillClient.fill(inFill, jTxtKey.getText());
        
        // lettura campi generali del risultato
        jTxtEsito.setText(String.valueOf(totOut.getNorm()));
        jTxtCodErr.setText(String.valueOf(totOut.getCodErr()));
        jTxtNumCand.setText(String.valueOf(totOut.getNumCand()));
        curCand=0;
        
        // dettaglio del primo candidato se esiste
        // nella form di output e' riportato solo un sottoinsieme di tutti i valori restituiti 
        if (totOut.getNumCand()>0)
        {
            jTxtRegioneOut.setText(totOut.getOutItem().get(curCand).getDetail().getRegione());
            jTxtComuneOut.setText(totOut.getOutItem().get(curCand).getComune());
            jTxtProvOut.setText(totOut.getOutItem().get(curCand).getProvincia());
            jTxtCAPOut.setText(totOut.getOutItem().get(curCand).getCap());
            jTxtIstatProvOut.setText(totOut.getOutItem().get(curCand).getDetail().getIstatProv());
            jTxtIstatComuneOut.setText(totOut.getOutItem().get(curCand).getDetail().getIstatComune());
            jTxtFrazioneOut.setText(totOut.getOutItem().get(curCand).getFrazione());
            jTxtIndirizzoOut.setText(totOut.getOutItem().get(curCand).getIndirizzo());
            jTxtXOut.setText(Double.toString(totOut.getOutItem().get(curCand).getGeo().getX()));
            jTxtYOut.setText(Double.toString(totOut.getOutItem().get(curCand).getGeo().getY()));
        }
    }//GEN-LAST:event_jBtnCallVerifyActionPerformed

    private void jBtnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrevActionPerformed
        // dettaglio del successivo candidato se esiste
        if (totOut.getNumCand()>0)
        {
            curCand-=1;
            jTxtRegioneOut.setText(totOut.getOutItem().get(curCand).getDetail().getRegione());
            jTxtComuneOut.setText(totOut.getOutItem().get(curCand).getComune());
            jTxtProvOut.setText(totOut.getOutItem().get(curCand).getProvincia());
            jTxtCAPOut.setText(totOut.getOutItem().get(curCand).getCap());
            jTxtIstatProvOut.setText(totOut.getOutItem().get(curCand).getDetail().getIstatProv());
            jTxtIstatComuneOut.setText(totOut.getOutItem().get(curCand).getDetail().getIstatComune());
            jTxtFrazioneOut.setText(totOut.getOutItem().get(curCand).getFrazione());
            jTxtIndirizzoOut.setText(totOut.getOutItem().get(curCand).getIndirizzo());
            jTxtXOut.setText(Double.toString(totOut.getOutItem().get(curCand).getGeo().getX()));
            jTxtYOut.setText(Double.toString(totOut.getOutItem().get(curCand).getGeo().getY()));
        }
    }//GEN-LAST:event_jBtnPrevActionPerformed

    private void jBtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNextActionPerformed
        // dettagli del precedente candidato se esiste
        if (curCand<totOut.getNumCand()-1)
        {
            curCand+=1;
            jTxtRegioneOut.setText(totOut.getOutItem().get(curCand).getDetail().getRegione());
            jTxtComuneOut.setText(totOut.getOutItem().get(curCand).getComune());
            jTxtProvOut.setText(totOut.getOutItem().get(curCand).getProvincia());
            jTxtCAPOut.setText(totOut.getOutItem().get(curCand).getCap());
            jTxtIstatProvOut.setText(totOut.getOutItem().get(curCand).getDetail().getIstatProv());
            jTxtIstatComuneOut.setText(totOut.getOutItem().get(curCand).getDetail().getIstatComune());
            jTxtFrazioneOut.setText(totOut.getOutItem().get(curCand).getFrazione());
            jTxtIndirizzoOut.setText(totOut.getOutItem().get(curCand).getIndirizzo());
            jTxtXOut.setText(Double.toString(totOut.getOutItem().get(curCand).getGeo().getX()));
            jTxtYOut.setText(Double.toString(totOut.getOutItem().get(curCand).getGeo().getY()));
        }
    }//GEN-LAST:event_jBtnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDemoFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDemoFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDemoFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDemoFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormDemoFill().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCallVerify;
    private javax.swing.JButton jBtnNext;
    private javax.swing.JButton jBtnPrev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCand;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelOut;
    private javax.swing.JTextField jTxtCAPIn;
    private javax.swing.JTextField jTxtCAPOut;
    private javax.swing.JTextField jTxtCodErr;
    private javax.swing.JTextField jTxtComuneIn;
    private javax.swing.JTextField jTxtComuneOut;
    private javax.swing.JTextField jTxtEsito;
    private javax.swing.JTextField jTxtFrazioneOut;
    private javax.swing.JTextField jTxtIndirizzoIn;
    private javax.swing.JTextField jTxtIndirizzoOut;
    private javax.swing.JTextField jTxtIstatComuneOut;
    private javax.swing.JTextField jTxtIstatProvOut;
    private javax.swing.JTextField jTxtKey;
    private javax.swing.JTextField jTxtNumCand;
    private javax.swing.JTextField jTxtProvIn;
    private javax.swing.JTextField jTxtProvOut;
    private javax.swing.JTextField jTxtRegioneOut;
    private javax.swing.JTextField jTxtXOut;
    private javax.swing.JTextField jTxtYOut;
    // End of variables declaration//GEN-END:variables
}
